// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"
)

type Category struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Detail struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Category  string    `json:"category"`
	Cost      int64     `json:"cost"`
	Date      time.Time `json:"date"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
}
